name: Build and deploy
on: push
env:
  REDDIT_USERNAME: AnimeMod
  REDDIT_PASSWORD:  ${{ secrets.ANIMEMOD_PASSWORD }}
  REDDIT_CLIENT_ID: ${{ secrets.STYLESHEET_CLIENT_ID }}
  REDDIT_CLIENT_SECRET: ${{ secrets.STYLESHEET_CLIENT_SECRET }}
  REDDIT_REDIRECT_URI: ${{ secrets.STYLESHEET_REDIRECT_URI }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and some other testing stuff
      run: |
        echo "${{ github.ref }}"
        python utils/validate.py
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-with-dart-sass
        path: test.md

  deploy-production:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to /r/anime
      env:
        REDDIT_SUBREDDIT: anime
      run: |
        python utils/build.py
        python utils/update.py

  deploy-staging:
    if: ${{ github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to /r/animestaging
      env:
        REDDIT_SUBREDDIT: animestaging
      run: |
        python utils/build.py
        python utils/update.py
