name: Build and deploy
on: push
env:
  REDDIT_USERNAME: AnimeMod
  REDDIT_PASSWORD:  ${{ secrets.ANIMEMOD_PASSWORD }}
  REDDIT_CLIENT_ID: ${{ secrets.STYLESHEET_CLIENT_ID }}
  REDDIT_CLIENT_SECRET: ${{ secrets.STYLESHEET_CLIENT_SECRET }}
  REDDIT_REDIRECT_URI: ${{ secrets.STYLESHEET_REDIRECT_URI }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install pip requirements
      run: pip install -r utils/requirements.txt
    - name: Build and some other testing stuff
      run: |
        echo ${{ github.ref }}
        python utils/validate.py
        ls -R
    - name: Upload generated CSS
      uses: actions/upload-artifact@v2
      with:
        name: stylesheet.css
        path: stylesheet.css
    - name: Upload generated subreddit data
      uses: actions/upload-artifact@v2
      with:
        name: subreddit_data.yml
        path: subreddit_data.yml

  deploy-production:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install pip requirements
      run: pip install -r utils/requirements.txt
    - name: Deploy to /r/anime
      env:
        REDDIT_SUBREDDIT: anime
      run: |
        python utils/build.py -r "${{ github.event.compare }}"
        python utils/update.py

  deploy-staging:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install pip requirements
      run: pip install -r utils/requirements.txt
    - name: Deploy to /r/animestaging
      env:
        REDDIT_SUBREDDIT: animestaging
      run: |
        python utils/build.py -r "${{ github.event.compare }}"
        python utils/update.py
